### ISSUE TITLE
REST API v2 Improvements

### ISSUE THREAD

**Issue by jpmadrigal07** [explore-siargao/es-main#1]
**Stories**

- [x] explore-siargao/es-main#2 
- [x] explore-siargao/es-main#3 
- [x] explore-siargao/es-main#4 
- [x] explore-siargao/es-main#5 
- [x] explore-siargao/es-main#6 
- [x] #11
