### ISSUE TITLE
[Feature] Implement Payments Metods and coupons REST-API V2 and Test

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#4]
**Tasks List**
- [ ] [Task] Add Payment Method
- [ ] [Task] Update Payment Method
- [ ] [Task] Remove Payment Method
- [ ] [Task] Get Payment Methods
- [ ] [Task] Update Coupons
